name: Compile and publish PDF
on: [ push, workflow_dispatch ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Cascadia Code font
        run: |
            mkdir -p ~/.fonts
            wget -O ~/.fonts/CascadiaCode.ttf https://github.com/microsoft/cascadia-code/releases/download/v2404.23/CascadiaCode-2404.23.zip
            unzip ~/.fonts/CascadiaCode.zip -d ~/.fonts
            fc-cache -f -v

      - name: Compile PDF
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            main.typ

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: BachelorThesis
          path: main.pdf

      - name: Get current date
        id: date
        run: echo "DATE=$(date %d.%m.+%Y)" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: main.pdf